/**
 * Catálogo seed das ~200 marcas mais populares (Brasil + mundo), usado no
 * onboarding (busca → Enter → agrega). Seedado no banco no boot (idempotente,
 * upsert por slug) por BrandCatalogService. `country`: 'br' | 'global'.
 *
 * Não é uma lista fechada — admins podem inserir mais; serve de ponto de
 * partida abrangente para a busca de marcas patrocinadoras.
 */
export interface BrandSeed {
  name: string;
  sector: string;
  country: 'br' | 'global';
  aliases?: string[];
}

export const BRAND_CATALOG_SEED: BrandSeed[] = [
  // ── Tecnologia / Hardware ────────────────────────────────────────────────
  { name: 'Apple', sector: 'tech', country: 'global' },
  { name: 'Samsung', sector: 'tech', country: 'global' },
  { name: 'Google', sector: 'tech', country: 'global' },
  { name: 'Microsoft', sector: 'tech', country: 'global' },
  { name: 'Sony', sector: 'tech', country: 'global' },
  { name: 'Intel', sector: 'tech', country: 'global' },
  { name: 'AMD', sector: 'tech', country: 'global' },
  { name: 'NVIDIA', sector: 'tech', country: 'global', aliases: ['nvidia', 'rtx', 'geforce'] },
  { name: 'Logitech', sector: 'tech', country: 'global', aliases: ['logi', 'logitech g'] },
  { name: 'Razer', sector: 'tech', country: 'global' },
  { name: 'HyperX', sector: 'tech', country: 'global' },
  { name: 'Corsair', sector: 'tech', country: 'global' },
  { name: 'SteelSeries', sector: 'tech', country: 'global' },
  { name: 'Elgato', sector: 'tech', country: 'global' },
  { name: 'ASUS', sector: 'tech', country: 'global', aliases: ['rog', 'republic of gamers'] },
  { name: 'MSI', sector: 'tech', country: 'global' },
  { name: 'Acer', sector: 'tech', country: 'global', aliases: ['predator'] },
  { name: 'Dell', sector: 'tech', country: 'global', aliases: ['alienware'] },
  { name: 'HP', sector: 'tech', country: 'global', aliases: ['omen', 'hewlett packard'] },
  { name: 'Lenovo', sector: 'tech', country: 'global', aliases: ['legion'] },
  { name: 'Xiaomi', sector: 'tech', country: 'global' },
  { name: 'Motorola', sector: 'tech', country: 'global', aliases: ['moto'] },
  { name: 'LG', sector: 'tech', country: 'global' },
  { name: 'JBL', sector: 'tech', country: 'global' },
  { name: 'Bose', sector: 'tech', country: 'global' },
  { name: 'GoPro', sector: 'tech', country: 'global' },
  { name: 'Redragon', sector: 'tech', country: 'global' },
  { name: 'Multilaser', sector: 'tech', country: 'br' },
  { name: 'Fortrek', sector: 'tech', country: 'br' },
  { name: 'Husky', sector: 'tech', country: 'br' },
  { name: 'Pichau', sector: 'tech', country: 'br' },
  { name: 'Kabum', sector: 'retail', country: 'br', aliases: ['kabum!'] },
  { name: 'Terabyte', sector: 'retail', country: 'br', aliases: ['terabyteshop'] },

  // ── Games / Plataformas ──────────────────────────────────────────────────
  {
    name: 'PlayStation',
    sector: 'gaming',
    country: 'global',
    aliases: ['ps5', 'ps4', 'sony playstation'],
  },
  { name: 'Xbox', sector: 'gaming', country: 'global', aliases: ['xbox series'] },
  { name: 'Nintendo', sector: 'gaming', country: 'global', aliases: ['switch'] },
  { name: 'Steam', sector: 'gaming', country: 'global' },
  { name: 'Epic Games', sector: 'gaming', country: 'global', aliases: ['epic'] },
  {
    name: 'Riot Games',
    sector: 'gaming',
    country: 'global',
    aliases: ['riot', 'league of legends', 'valorant'],
  },
  { name: 'Electronic Arts', sector: 'gaming', country: 'global', aliases: ['ea', 'ea sports'] },
  { name: 'Ubisoft', sector: 'gaming', country: 'global' },
  { name: 'Rockstar Games', sector: 'gaming', country: 'global', aliases: ['rockstar', 'gta'] },
  { name: 'Activision', sector: 'gaming', country: 'global', aliases: ['call of duty', 'cod'] },
  { name: 'Blizzard', sector: 'gaming', country: 'global' },
  { name: 'Garena', sector: 'gaming', country: 'global', aliases: ['free fire'] },
  { name: 'Roblox', sector: 'gaming', country: 'global' },
  {
    name: 'Supercell',
    sector: 'gaming',
    country: 'global',
    aliases: ['clash royale', 'clash of clans'],
  },
  { name: 'Mojang', sector: 'gaming', country: 'global', aliases: ['minecraft'] },
  {
    name: 'Valve',
    sector: 'gaming',
    country: 'global',
    aliases: ['cs2', 'counter strike', 'dota'],
  },
  { name: 'miHoYo', sector: 'gaming', country: 'global', aliases: ['hoyoverse', 'genshin impact'] },
  { name: 'Tencent', sector: 'gaming', country: 'global' },

  // ── Streaming / Apps / Social ────────────────────────────────────────────
  { name: 'Twitch', sector: 'streaming', country: 'global' },
  { name: 'Kick', sector: 'streaming', country: 'global' },
  { name: 'YouTube', sector: 'streaming', country: 'global', aliases: ['yt', 'youtube premium'] },
  { name: 'Netflix', sector: 'streaming', country: 'global' },
  { name: 'Disney+', sector: 'streaming', country: 'global', aliases: ['disney plus', 'disney'] },
  { name: 'Prime Video', sector: 'streaming', country: 'global', aliases: ['amazon prime'] },
  { name: 'Max', sector: 'streaming', country: 'global', aliases: ['hbo max', 'hbo'] },
  { name: 'Spotify', sector: 'streaming', country: 'global' },
  { name: 'Crunchyroll', sector: 'streaming', country: 'global' },
  { name: 'Discord', sector: 'tech', country: 'global' },
  { name: 'TikTok', sector: 'social', country: 'global' },
  { name: 'Instagram', sector: 'social', country: 'global', aliases: ['insta', 'meta'] },
  { name: 'WhatsApp', sector: 'social', country: 'global', aliases: ['zap'] },
  { name: 'Telegram', sector: 'social', country: 'global' },
  { name: 'X', sector: 'social', country: 'global', aliases: ['twitter'] },
  { name: 'Reddit', sector: 'social', country: 'global' },
  { name: 'Snapchat', sector: 'social', country: 'global' },
  { name: 'OpenAI', sector: 'tech', country: 'global', aliases: ['chatgpt', 'gpt'] },

  // ── Energéticos / Bebidas ────────────────────────────────────────────────
  { name: 'Red Bull', sector: 'beverage', country: 'global', aliases: ['redbull'] },
  { name: 'Monster Energy', sector: 'beverage', country: 'global', aliases: ['monster'] },
  { name: 'Rockstar Energy', sector: 'beverage', country: 'global' },
  { name: 'G Fuel', sector: 'beverage', country: 'global', aliases: ['gfuel'] },
  { name: 'Gamer Supps', sector: 'beverage', country: 'global', aliases: ['gamersupps'] },
  { name: 'Baly', sector: 'beverage', country: 'br' },
  { name: 'TNT Energy', sector: 'beverage', country: 'br', aliases: ['tnt'] },
  { name: 'Fusion', sector: 'beverage', country: 'br' },
  {
    name: 'Coca-Cola',
    sector: 'beverage',
    country: 'global',
    aliases: ['coca', 'cocacola', 'coca cola'],
  },
  { name: 'Pepsi', sector: 'beverage', country: 'global' },
  {
    name: 'Guaraná Antarctica',
    sector: 'beverage',
    country: 'br',
    aliases: ['guarana', 'guaraná'],
  },
  { name: 'Gatorade', sector: 'beverage', country: 'global' },
  { name: 'Nescafé', sector: 'beverage', country: 'global', aliases: ['nescafe'] },
  { name: 'Heineken', sector: 'beverage', country: 'global' },
  { name: 'Budweiser', sector: 'beverage', country: 'global', aliases: ['bud'] },
  { name: 'Corona', sector: 'beverage', country: 'global' },
  { name: 'Brahma', sector: 'beverage', country: 'br' },
  { name: 'Skol', sector: 'beverage', country: 'br' },
  { name: 'Antarctica', sector: 'beverage', country: 'br' },
  { name: 'Itaipava', sector: 'beverage', country: 'br' },
  { name: 'Ambev', sector: 'beverage', country: 'br' },
  { name: 'Red Label', sector: 'beverage', country: 'global' },

  // ── Comida / Fast-food / Delivery ────────────────────────────────────────
  {
    name: "McDonald's",
    sector: 'food',
    country: 'global',
    aliases: ['mcdonalds', 'mc donalds', 'mcdonald'],
  },
  { name: 'Burger King', sector: 'food', country: 'global', aliases: ['bk'] },
  { name: 'KFC', sector: 'food', country: 'global' },
  { name: 'Subway', sector: 'food', country: 'global' },
  { name: 'Starbucks', sector: 'food', country: 'global' },
  { name: "Domino's", sector: 'food', country: 'global', aliases: ['dominos'] },
  { name: 'Pizza Hut', sector: 'food', country: 'global' },
  { name: "Habib's", sector: 'food', country: 'br', aliases: ['habibs'] },
  { name: "Bob's", sector: 'food', country: 'br', aliases: ['bobs'] },
  { name: 'Giraffas', sector: 'food', country: 'br' },
  { name: 'iFood', sector: 'food', country: 'br', aliases: ['ifood'] },
  { name: 'Rappi', sector: 'food', country: 'br' },
  { name: 'Nestlé', sector: 'food', country: 'global', aliases: ['nestle'] },
  { name: 'Nutella', sector: 'food', country: 'global' },
  { name: 'Pringles', sector: 'food', country: 'global' },
  { name: 'Doritos', sector: 'food', country: 'global' },
  { name: "Lay's", sector: 'food', country: 'global', aliases: ['lays', 'elma chips'] },
  { name: 'Oreo', sector: 'food', country: 'global' },
  { name: 'Bauducco', sector: 'food', country: 'br' },
  { name: 'Bis', sector: 'food', country: 'br' },
  { name: 'Trident', sector: 'food', country: 'global' },
  { name: 'Halls', sector: 'food', country: 'global' },
  { name: 'Sadia', sector: 'food', country: 'br' },
  { name: 'Perdigão', sector: 'food', country: 'br', aliases: ['perdigao'] },
  { name: 'Friboi', sector: 'food', country: 'br' },
  { name: 'Seara', sector: 'food', country: 'br' },
  { name: 'Feastables', sector: 'food', country: 'global', aliases: ['mr beast', 'mrbeast'] },

  // ── Moda / Esporte / Beleza ──────────────────────────────────────────────
  { name: 'Nike', sector: 'fashion', country: 'global' },
  { name: 'Adidas', sector: 'fashion', country: 'global' },
  { name: 'Puma', sector: 'fashion', country: 'global' },
  { name: 'Under Armour', sector: 'fashion', country: 'global' },
  { name: 'Reebok', sector: 'fashion', country: 'global' },
  { name: 'Vans', sector: 'fashion', country: 'global' },
  { name: 'Converse', sector: 'fashion', country: 'global' },
  { name: 'New Balance', sector: 'fashion', country: 'global' },
  { name: 'Lacoste', sector: 'fashion', country: 'global' },
  { name: 'Supreme', sector: 'fashion', country: 'global' },
  { name: 'The North Face', sector: 'fashion', country: 'global' },
  { name: 'Zara', sector: 'fashion', country: 'global' },
  { name: 'H&M', sector: 'fashion', country: 'global', aliases: ['hm'] },
  { name: "Levi's", sector: 'fashion', country: 'global', aliases: ['levis'] },
  { name: 'Gucci', sector: 'fashion', country: 'global' },
  { name: 'Louis Vuitton', sector: 'fashion', country: 'global', aliases: ['lv'] },
  { name: 'Havaianas', sector: 'fashion', country: 'br' },
  { name: 'Osklen', sector: 'fashion', country: 'br' },
  { name: 'Centauro', sector: 'retail', country: 'br' },
  { name: 'Natura', sector: 'beauty', country: 'br' },
  { name: 'O Boticário', sector: 'beauty', country: 'br', aliases: ['boticario'] },
  { name: 'Avon', sector: 'beauty', country: 'global' },
  { name: 'Gillette', sector: 'beauty', country: 'global' },
  { name: 'Nivea', sector: 'beauty', country: 'global' },
  { name: 'Dove', sector: 'beauty', country: 'global' },
  { name: 'Old Spice', sector: 'beauty', country: 'global' },

  // ── Varejo / E-commerce ──────────────────────────────────────────────────
  { name: 'Amazon', sector: 'retail', country: 'global' },
  { name: 'Mercado Livre', sector: 'retail', country: 'br', aliases: ['mercadolivre', 'meli'] },
  { name: 'Shopee', sector: 'retail', country: 'global' },
  { name: 'AliExpress', sector: 'retail', country: 'global', aliases: ['aliexpress'] },
  { name: 'Shein', sector: 'retail', country: 'global' },
  { name: 'Magazine Luiza', sector: 'retail', country: 'br', aliases: ['magalu'] },
  { name: 'Casas Bahia', sector: 'retail', country: 'br' },
  { name: 'Americanas', sector: 'retail', country: 'br' },
  { name: 'Ponto', sector: 'retail', country: 'br', aliases: ['ponto frio'] },
  { name: 'eBay', sector: 'retail', country: 'global' },

  // ── Bancos / Fintech / Pagamentos / Cripto ───────────────────────────────
  { name: 'Nubank', sector: 'finance', country: 'br' },
  { name: 'PicPay', sector: 'finance', country: 'br', aliases: ['picpay'] },
  { name: 'Mercado Pago', sector: 'finance', country: 'br', aliases: ['mercadopago'] },
  { name: 'PagBank', sector: 'finance', country: 'br', aliases: ['pagseguro'] },
  { name: 'Banco Inter', sector: 'finance', country: 'br', aliases: ['inter'] },
  { name: 'C6 Bank', sector: 'finance', country: 'br', aliases: ['c6'] },
  { name: 'Itaú', sector: 'finance', country: 'br', aliases: ['itau'] },
  { name: 'Bradesco', sector: 'finance', country: 'br' },
  { name: 'Banco do Brasil', sector: 'finance', country: 'br', aliases: ['bb'] },
  { name: 'Santander', sector: 'finance', country: 'br' },
  { name: 'Caixa', sector: 'finance', country: 'br', aliases: ['caixa economica'] },
  { name: 'XP Investimentos', sector: 'finance', country: 'br', aliases: ['xp'] },
  { name: 'Stone', sector: 'finance', country: 'br' },
  { name: 'Visa', sector: 'finance', country: 'global' },
  { name: 'Mastercard', sector: 'finance', country: 'global' },
  { name: 'PayPal', sector: 'finance', country: 'global', aliases: ['paypal'] },
  { name: 'Binance', sector: 'crypto', country: 'global' },
  { name: 'Coinbase', sector: 'crypto', country: 'global' },
  { name: 'Mercado Bitcoin', sector: 'crypto', country: 'br' },

  // ── Telecom ──────────────────────────────────────────────────────────────
  { name: 'Vivo', sector: 'telecom', country: 'br' },
  { name: 'Claro', sector: 'telecom', country: 'br' },
  { name: 'TIM', sector: 'telecom', country: 'br' },
  { name: 'Oi', sector: 'telecom', country: 'br' },

  // ── Mobilidade / Automotivo ──────────────────────────────────────────────
  { name: 'Uber', sector: 'mobility', country: 'global' },
  { name: '99', sector: 'mobility', country: 'br', aliases: ['99app'] },
  { name: 'Toyota', sector: 'automotive', country: 'global' },
  { name: 'Honda', sector: 'automotive', country: 'global' },
  { name: 'Volkswagen', sector: 'automotive', country: 'global', aliases: ['vw'] },
  { name: 'Ford', sector: 'automotive', country: 'global' },
  { name: 'Chevrolet', sector: 'automotive', country: 'global', aliases: ['gm'] },
  { name: 'Fiat', sector: 'automotive', country: 'global' },
  { name: 'Jeep', sector: 'automotive', country: 'global' },
  { name: 'BMW', sector: 'automotive', country: 'global' },
  { name: 'Mercedes-Benz', sector: 'automotive', country: 'global', aliases: ['mercedes'] },
  { name: 'Audi', sector: 'automotive', country: 'global' },
  { name: 'Porsche', sector: 'automotive', country: 'global' },
  { name: 'Tesla', sector: 'automotive', country: 'global' },
  { name: 'Hyundai', sector: 'automotive', country: 'global' },
  { name: 'Nissan', sector: 'automotive', country: 'global' },

  // ── Apostas / Cassino (grande no streaming BR) ───────────────────────────
  { name: 'Betano', sector: 'betting', country: 'br' },
  { name: 'bet365', sector: 'betting', country: 'global', aliases: ['bet 365'] },
  { name: 'Blaze', sector: 'betting', country: 'br' },
  { name: 'Stake', sector: 'betting', country: 'global' },
  { name: 'Sportingbet', sector: 'betting', country: 'global' },
  { name: 'Betfair', sector: 'betting', country: 'global' },
  { name: 'KTO', sector: 'betting', country: 'br' },
  { name: 'Esportes da Sorte', sector: 'betting', country: 'br' },
  { name: 'F12 Bet', sector: 'betting', country: 'br', aliases: ['f12bet', 'f12'] },
  { name: 'Pixbet', sector: 'betting', country: 'br' },
  { name: 'Realsbet', sector: 'betting', country: 'br' },
  { name: 'Galera.bet', sector: 'betting', country: 'br', aliases: ['galera bet'] },
  { name: 'Superbet', sector: 'betting', country: 'br' },
  { name: 'EstrelaBet', sector: 'betting', country: 'br', aliases: ['estrela bet'] },

  // ── Outras marcas fortes em patrocínio de creators ───────────────────────
  { name: 'Spotify Premium', sector: 'streaming', country: 'global' },
  { name: 'NordVPN', sector: 'tech', country: 'global' },
  { name: 'ExpressVPN', sector: 'tech', country: 'global' },
  { name: 'Hostinger', sector: 'tech', country: 'global' },
  { name: 'Domino', sector: 'food', country: 'global' },
  { name: 'Lenovo Legion', sector: 'tech', country: 'global' },
  { name: 'Logitech G', sector: 'tech', country: 'global' },
  { name: 'AOC', sector: 'tech', country: 'global' },
  { name: 'Samsung Odyssey', sector: 'tech', country: 'global' },
  { name: 'Positivo', sector: 'tech', country: 'br' },
  { name: 'Intelbras', sector: 'tech', country: 'br' },
  { name: 'Brahma Duplo Malte', sector: 'beverage', country: 'br' },
  { name: 'Monster Ultra', sector: 'beverage', country: 'global' },
];
